kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ template "retool.fullname" . }}-configmap"
data: 
  use-insecure-cookies: {{ .Values.config.useInsecureCookies | quote }}
  
  postgres-host: {{ .Values.config.postgres.host | quote }}
  postgres-port: {{ .Values.config.postgres.port | quote }}
  postgres-db: {{ .Values.config.postgres.db | quote }}
  postgres-user: {{ .Values.config.postgres.user | quote }}

  {{- if .Values.config.auth.google.clientId }}
  google-client-id: {{ .Values.config.auth.google.clientId | quote }}
  {{- else }}
  google-client-id: ""
  {{- end }}
  
  {{- if .Values.config.auth.google.domain }}
  restricted-domain: {{ .Values.config.auth.google.domain | quote }}
  {{- else }}
  restricted-domain: ""
  {{- end }}
